name: RedstoneSimPlugin
version: '${version}'
main: io.github.daylightnebula.redstonesimplugin.RedstoneSimPlugin
api-version: '1.20'
commands:
  setup:
    description: Setup for building
    usage: /setup <width> <height> <depth>
  run:
    description: Run tests
    usage: /run <number of runners, this number will be tripled>